### PR TITLE
SCA Local Source Scanning (Zip Upload) via CLI/Batch

### PR DESCRIPTION
**Pull request by kmcdon83**
By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](https://github.com/checkmarx-ts/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/checkmarx-ltd/open-source-template/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

This PR is to introduce the option for SCA scanning through CLI/Batch execution.  The default scanner is sast if nothing is provided, otherwise the CLI execution will honor the enabled scanners from the configuration (sca/sast)

### Testing

Manual testing has been conducted to validate execution of both SAST/SCA when the vulnerability scanners are specified in the configuration.

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentaiton is a Wiki Update, please indicate desired changes within PR MD Comment*
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used

### CODE REVIEW

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by AvivCX** [comment]
@alex-ko-dev , can you please help to pass automation tests for this PR?

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by kmcdon83** [comment]
> There are something here that should be written in java 8 style,
> Some of the logic should be moved to vulnerabilityScanner,
> the dependency in sastscanner and scascanner should be removed.
> 
> I approve this commit for its functionality, we will fix the issues in this commit in the User story 192.
> we will also add automated tests in a later issue (on the backlog)

CLI logic should be broken down differently longterm.  This will get the functionality working in the meantime.

Thanks.

**Pull request merged**
