### PR TITLE
SARIF Report Output Support

### LINKED ISSUE #385: Add support for SARIF Output Format
### Describe the problem

Currently there is no support for the OASIS SARIF output specification

### Proposed solution

Implement a new bug-tracker to support SARIF report format (JSON)

### Additional details

This is in support of building GitHub Action support for GitHub's upcoming CodeQL feature.
https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/sarif-support-for-code-scanning
https://www.oasis-open.org/committees/sarif/

### PR DESCRIPTION
**Pull request by kmcdon83**
By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](https://github.com/checkmarx-ts/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/checkmarx-ltd/open-source-template/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

Introducing "Sarif" as an applicable bug tracker that will produce a JSON report file that meets the GitHub Specification for SARIF as maintained by OASIS

### References

Fixes #385 
Documentation will be added for usage on the published GitHub Action [WIP]: 
https://github.com/checkmarx-ts/checkmarx-cxflow-github-action

### Testing

Unit Tests are included in PR.
The following GitHub Action test is leveraging a pre-release docker image.  GitHub produces Security Alerts when SARIF is uploaded
Screen Shot 2020-08-12 at 7 06 33 PM

### Checklist

- [x] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentaiton is a Wiki Update, please indicate desired changes within PR MD Comment*
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used

### CODE REVIEW

**Comment by kmcdon83** [comment]
@AvivCX , there is a lot of commit history due to debugging GitHub Actions with SARIF output to get things running as desired.  These will be squashed as we merge for cleaner code.  

The changes are minimal and limited to adding a Property Class and Bug Tracker implementation with some unit tests.

**Comment by kmcdon83** [comment]
> Kudos, SonarCloud Quality Gate passed!
> 
> [Bug](https://sonarcloud.io/project/issues?id=checkmarx-ltd_cx-flow&pullRequest=386&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=checkmarx-ltd_cx-flow&pullRequest=386&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=checkmarx-ltd_cx-flow&pullRequest=386&resolved=false&types=BUG)
> [Vulnerability](https://sonarcloud.io/project/issues?id=checkmarx-ltd_cx-flow&pullRequest=386&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=checkmarx-ltd_cx-flow&pullRequest=386&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=checkmarx-ltd_cx-flow&pullRequest=386&resolved=false&types=VULNERABILITY) (and [Security Hotspot](https://sonarcloud.io/project/issues?id=checkmarx-ltd_cx-flow&pullRequest=386&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/issues?id=checkmarx-ltd_cx-flow&pullRequest=386&resolved=false&types=SECURITY_HOTSPOT) to review)
> [Code Smell](https://sonarcloud.io/project/issues?id=checkmarx-ltd_cx-flow&pullRequest=386&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=checkmarx-ltd_cx-flow&pullRequest=386&resolved=false&types=CODE_SMELL) [1 Code Smell](https://sonarcloud.io/project/issues?id=checkmarx-ltd_cx-flow&pullRequest=386&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=checkmarx-ltd_cx-flow&pullRequest=386&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=checkmarx-ltd_cx-flow&pullRequest=386&metric=new_coverage&view=list)
> [](https://sonarcloud.io/component_measures?id=checkmarx-ltd_cx-flow&pullRequest=386&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=checkmarx-ltd_cx-flow&pullRequest=386&metric=new_duplicated_lines_density&view=list)
> 
> warning The version of Java (1.8.0_265) you have used to run this analysis is deprecated and we will stop accepting it from October 2020. Please update to at least Java 11.
> Read more [here](https://sonarcloud.io/documentation/upcoming/)

Latest update removed this code smell, not sure why latest report has it showing here.

**Comment by rjbell4** [comment]
The documentation does not seem to have been updated to reference Sarif output

**Comment by jbrotsos** [comment]
Hey @rjbell4 

Are you trying to use SARIF output for GitHub Action integration?

**Comment by rjbell4** [comment]
@jbrotsos I was going to attempt to use it outside of GitHub Actions, though now AFAICT you need to use an Action to upload the SARIF file...

**Comment by jbrotsos** [comment]
Hey @rjbell4 

I modified the YAML file with the following edits:
cx-flow:
  bug-tracker: Sarif
  bug-tracker-impl:
    - Sarif

Then, I ran CxFlow in batch mode:

java -jar "build/libs/cx-flow.jar" \
--spring.config.location="config/cli_batch-sarif-9_0.yml" \
--batch \
--cx-team="CxServer/cxflow" \
--cx-project="Project-main"

And a file named cx.sarif is created in the directory you run the java command in.  Let me know if that works for you.

**Comment by rjbell4** [comment]
@jbrotsos My apologies if I haven't been clear, but I wasn't specifically asking for directions (which I might or might not have been able to figure out myself).  It was more that I was looking for documentation, and found that this capability was added to CxFlow several months ago, but the documentation hasn't been updated, and still doesn't refer to SARIF in any way.  It would be best for *all* users of the documentation was an accurate reflection of the current functionality.

**Comment by jbrotsos** [comment]
Hey @rjbell4, our SARIF support is meant for GitHub Security integration / partnership, though you can use it as an output.  We don't have customers using it for report generation.  Here is the documentation we have for our GitHub Action:

https://github.com/checkmarx-ts/checkmarx-cxflow-github-action

**Pull request merged**
