### PR TITLE
SCA project team assignment test & WIKI minor amendments

### PR DESCRIPTION
**Pull request by NimrodGolan**
### Description

> SCA project team assignment test & WIKI minor amendments

### References

> [User Story](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/495)

### Checklist

- [X] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentation is a Wiki Update, please indicate desired changes within PR MD Comment*
- [X] All active GitHub checks for tests, formatting, and security are passing
- [X] The correct base branch is being used

### CODE REVIEW

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Review by alex-ko-dev — APPROVED** [review]

**Comment by cxflowtestuser** [comment]
Logo<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 1486 vulnerabilities<br />High&nbsp;**0 High**<br />Medium&nbsp;**46 Medium**<br />Low&nbsp;**1332 Low**<br />Info&nbsp;**108 Info**<br />
### Violation Summary
Medium&nbsp;**11** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1051220&projectid=1071)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[100](https://github.com/checkmarx-ltd/cx-flow/blob/pr-nimrod-sca-team-amendments/src/main/java/com/checkmarx/flow/controller/GitHubController.java#L100) [241](https://github.com/checkmarx-ltd/cx-flow/blob/pr-nimrod-sca-team-amendments/src/main/java/com/checkmarx/flow/controller/GitHubController.java#L241) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/controller/GitHubController.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1051220&projectid=1071&pathid=7)
[213](https://github.com/checkmarx-ltd/cx-flow/blob/pr-nimrod-sca-team-amendments/src/main/java/com/checkmarx/flow/utils/ScanUtils.java#L213) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/utils/ScanUtils.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1051220&projectid=1071&pathid=3)
[60](https://github.com/checkmarx-ltd/cx-flow/blob/pr-nimrod-sca-team-amendments/src/main/java/com/checkmarx/flow/service/ExternalScriptService.java#L60) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/service/ExternalScriptService.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1051220&projectid=1071&pathid=48)
[253](https://github.com/checkmarx-ltd/cx-flow/blob/pr-nimrod-sca-team-amendments/src/main/java/com/checkmarx/flow/controller/BitbucketServerController.java#L253) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/controller/BitbucketServerController.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1051220&projectid=1071&pathid=44)
[67](https://github.com/checkmarx-ltd/cx-flow/blob/pr-nimrod-sca-team-amendments/src/main/java/com/checkmarx/flow/controller/FlowController.java#L67) [70](https://github.com/checkmarx-ltd/cx-flow/blob/pr-nimrod-sca-team-amendments/src/main/java/com/checkmarx/flow/controller/FlowController.java#L70) [71](https://github.com/checkmarx-ltd/cx-flow/blob/pr-nimrod-sca-team-amendments/src/main/java/com/checkmarx/flow/controller/FlowController.java#L71) [76](https://github.com/checkmarx-ltd/cx-flow/blob/pr-nimrod-sca-team-amendments/src/main/java/com/checkmarx/flow/controller/FlowController.java#L76) [78](https://github.com/checkmarx-ltd/cx-flow/blob/pr-nimrod-sca-team-amendments/src/main/java/com/checkmarx/flow/controller/FlowController.java#L78) [137](https://github.com/checkmarx-ltd/cx-flow/blob/pr-nimrod-sca-team-amendments/src/main/java/com/checkmarx/flow/controller/FlowController.java#L137) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/controller/FlowController.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1051220&projectid=1071&pathid=19)

**Comment by brenwhyte** [comment]
Hi,

Where exactly can I set this?

Something like:

```
sca:
  appUrl: https://sca.checkmarx.net
  apiUrl: https://api-sca.checkmarx.net
  accessControlUrl: https://platform.checkmarx.net
  tenant: 
  username: 
  password: 
  team-for-new-projects: /CxServer/team/squad
```

I'd like to see this as config-as-code so I can submit a Feature request for that.

**Comment by NimrodGolan** [comment]
@brenwhyte - Hi, yes, exactly like you did.

@AvivCx - FYI.

**Comment by brenwhyte** [comment]
@NimrodGolan 

Great, thanks.
I did try with yesterday's 1.16.8 pre-release and it didn't work but I've updated to the nwer 1.16.8 released this morning and it's worked as expected now as per my previous post.

I've filed a separate issue to see if this can also be set as config-as-code
https://github.com/checkmarx-ltd/cx-flow/issues/634

Thank you!

**Pull request merged**
