### PR TITLE
Fix for Private GitHub and Auto Profile Issues

### LINKED ISSUE #134: Preset is never overridden when specified in WebHook parameters orin "sast" section in cx.config
Checkmarx version: 8.9.0 HF13 (SDLC)
CX-flow version: 1.5.4

When having a project already created in Checkmarx SAST, and CXflow is setup to generate scans on Pull Requests, the Checkmarx preset specified in the Pull Request Webhook parameter is never used. Instead, the preset defined in the application.yml is always used.

Use case:
Say that we have a CXFlow instance listening to Github PRs that triggers scans. The "scan-preset" property in application.yml not specified (intentionally), so that one can override the preset in the WebHook Parameter (as specified in GitHubController.Java in method:
public ResponseEntity<EventResponse> pullRequest

Observations:

the "override" is never used (greyed out by the IDE)
No matter what preset I specify in the WebHook parameter, the Checkmarx Default is always used
While debugging through the code, I noticed that in file FlowService.java, method
private Integer determinePresetAndProjectId(ScanRequest request, String ownerId, String projectName ) {

it seems that the check is wrongly done (unless I understood #the code logic wrong), and the method fetches and sets the project's preset if the request has the scanPresetOverride as false.
image

By removing the negation before the "request.isScanPresetOverride()", it works as expected and the scan will use the project's defined Preset (that was set from within the Web Interface).

I might have not understood the code logic, or maybe this is just a bug and the negation needs to be removed.

### PR DESCRIPTION
**Pull request by kmcdon83**
By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](https://github.com/checkmarx-ts/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/checkmarx-ltd/open-source-template/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

When scanning a private repository under an organization (not a user account) their are several failures within GitHub due to 404s and missing authentication headers within comments.

Additionally, the auto profiling logic was fixed.  Some cases would cause logic to be skipped inappropriately.

### References

Fixes #134 

### Testing

- Leverage existing Integration / E2E testing 
- Manual validation of GitHub Private Repo integration (non-user organization)

### Checklist

- [x] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentaiton is a Wiki Update, please indicate desired changes within PR MD Comment*
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used

### CODE REVIEW

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by cxflowtestuser** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1000126&projectid=53)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|549
Low|5797
Informational|44

#### Violation Summary
Severity|Count
---|---

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by cxflowtestuser** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1000156&projectid=53)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|549
Low|5867
Informational|44

#### Violation Summary
Severity|Count
---|---

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---

**Comment by AvivCX** [comment]
@kmcdon83 we added PR #243 to add your fixes.
if you approve the PR, this one can be closed

**Comment by kmcdon83** [comment]
Closing based on review of #239 and #243

**Pull request closed without merging**
