### PR TITLE
Pr ts feature/bb server pr feedback

### LINKED ISSUE #171: Enhance BitBucket Pull Feedback
Investigate and implement additional capabilities within BitBucket Pull Request feedback
 
- [x] Block Merge after scan completes, based on filter/policy criteria
- [ ] Provide diff view, to help determine if current commit/pull has introduced the finding
- [ ] Source snippet highlights as a comment. This would need to occur at the commit level (i.e. Violation comments as a reviewer on the file/commit). Checkmarx BB Service account would be a "reviewer" of the code. References:

https://wiki.jenkins.io/display/JENKINS/Violation+Comments+to+Bitbucket+Server+Plugin

### PR DESCRIPTION
**Pull request by MithileshPawar**
By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](https://github.com/checkmarx-ts/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/checkmarx-ltd/open-source-template/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

> Adds the support for merge checks available in BitBucket Server such as 1) Build Status and 2) Posting a comment or task as PR feedback after a scan is completed.

### References

> Fixes #171

### Testing

> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentaiton is a Wiki Update, please indicate desired changes within PR MD Comment*
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used

### CODE REVIEW

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by cxflowtestuser** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1000176&projectid=70)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|479
Low|4967
Informational|44

#### Violation Summary
Severity|Count
---|---

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by cxflowtestuser** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1000177&projectid=70)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|479
Low|4967
Informational|44

#### Violation Summary
Severity|Count
---|---

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by cxflowtestuser** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1000178&projectid=70)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|479
Low|4967
Informational|44

#### Violation Summary
Severity|Count
---|---

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---

**Comment by kmcdon83** [comment]
@natalieb07 @AvivCX changes are isolated to BitBucket functionality only.

**Pull request merged**
