### PR TITLE
Feature/bb post webhooks

### LINKED ISSUE #650: Bitbucket server MERGED event causes extra scans or error conditions
### Description

BB Server handles a MERGED event indicating a PR was merged, but this appears to attempt to initiate a scan on the FROM branch again and will update the PR comments post-merge if the branch was not deleted. 

If the user chose to delete the FROM branch on merge, CxFlow just errors out because the branch doesn't exist. When the FROM is not deleted, you get 2 scans submitted - the FROM branch (due to MERGED) and the TO branch (due to PUSH). 

### Expected Behavior

When a PR is MERGED, there should be no special handling.  It would be assumed the TO branch would generate a PUSH event that would invoke the scan/SCM update.

### Actual Behavior

MERGED attempts to scan the FROM branch with 2 outcomes:

1. Failure if the FROM branch has been deleted on merge.
2. Success if the FROM branch was not deleted, and a new PR comment is added.

### Reproduction
Use BB server to merge a PR to a protected branch.  If you delete the FROM branch, look at the CxFlow log to see an error.  If you don't delete the branch on merge, you'll see a new scan for the FROM branch.

### LINKED ISSUE #651: Bitbucket Server third party webhooks plugin "Post Webhooks" support
### Describe the problem

Customer requests the ability to support [Post Webhooks](https://marketplace.atlassian.com/apps/1215474/post-webhooks-for-bitbucket?hosting=server&tab=overview).

Mainly this is due to the ability to define webhooks on the global, team, and project level.  They want to set a single global webhook (BB Server doesn't support this) and use Config As Code to configure each repo.

### Proposed solution

The Post Webhook even names clash with both BB Cloud and BB Server implementations.  The handler will perform the same workflow as the current BB Server capability.  The `/postwebhook` path will allow the events to be handled without clashing with existing BB handlers.

### LINKED ISSUE #674: SCM Multi-instance not implemented for BitBucket Server
### Description

The BitBucket Server controller does not attempt to set the SCM instance such as is done in the ADO, GitLab, and GitHub controllers.

### Expected Behavior

SCM multi-instance works as documented for this SCM.

### Actual Behavior

Only a single SCM instance is supported

### Reproduction

1. Set up multi-SCM instance for this SCM
2. Handle a webhook from the non-default instance
3. Observe CxFlow attempting to interact with the default SCM instance

### LINKED ISSUE #699: Jira cloud Issue #499 broke "assignee" compatibility with Jira Data Center
### Description

Issue #499 fixed a problem where Jira cloud `assignee` override broke due to an API change.  The code at the time was using a Jira client library that appears to have abstracted the resolution of the account id.  I believe that client was deprecated, and a change was made to talk directly to the Jira REST API and retrieve `accountId` from the JSON response.  

It appears that the Atlassian announcements referenced in issue #499 applied only to Jira Cloud.  Using Jira Data Center v8.16 (latest), it clearly shows the response payload does not have `accountId` but uses `key` to hold the linking value used for `assignee`.

```
[
	{
		"self": "http://jira-server:8080/rest/api/2/user?username=admin",
		"key": "JIRAUSER10000",
		"name": "admin",
		"emailAddress": "bar@foo.com",
		"avatarUrls": {
			"48x48": "https://www.gravatar.com/avatar/dc8a42aba3651b0b1f088ef928ff3b1d?d=mm&s=48",
			"24x24": "https://www.gravatar.com/avatar/dc8a42aba3651b0b1f088ef928ff3b1d?d=mm&s=24",
			"16x16": "https://www.gravatar.com/avatar/dc8a42aba3651b0b1f088ef928ff3b1d?d=mm&s=16",
			"32x32": "https://www.gravatar.com/avatar/dc8a42aba3651b0b1f088ef928ff3b1d?d=mm&s=32"
		},
		"displayName": "bar@foo.com",
		"active": true,
		"deleted": false,
		"timeZone": "GMT",
		"locale": "en_US"
	}
]

```

### Expected Behavior

The `assignee` override via URL parameter or config-as-code should set the `assignee` field in Jira when creating an issue.  It should probe for `accountId` or `key` to ensure it is compatible with Jira Cloud, Jira Data Center, and any future changes to Jira Data Center should they decide to port the Jira Cloud API changes over to Jira Data Center.

### Actual Behavior

An exception is thrown and all issue creation is aborted.

```
org.json.JSONException: JSONObject["accountId"] not found.
	at org.json.JSONObject.get(JSONObject.java:572)
	at com.checkmarx.flow.service.JiraService.getAssignee(JiraService.java:795)
	at com.checkmarx.flow.service.JiraService.createIssue(JiraService.java:305)
	at com.checkmarx.flow.service.JiraService.createIssueAndAddToNewIssuesList(JiraService.java:1340)
	at com.checkmarx.flow.service.JiraService.process(JiraService.java:1247)
	at com.checkmarx.flow.service.ResultsService.handleJiraCase(ResultsService.java:229)
	at com.checkmarx.flow.service.ResultsService.processResults(ResultsService.java:137)
	at com.checkmarx.flow.service.ResultsService.publishCombinedResults(ResultsService.java:101)
	at com.checkmarx.flow.service.ResultsService$$FastClassBySpringCGLIB$$2328645f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

### Reproduction

1. Configure CxFlow to use [Jira Data Center](https://hub.docker.com/r/atlassian/jira-software).  In my case, I made an instance using the Docker image.
2. Use a URL or config as code override for `assignee`.
3. Make a change in a protected branch in CxFlow to invoke a scan via webhook, or use some other CxFlow invocation method that will push issues to Jira.
4. Observe exception and issue creation abort.

### Environment Details

Jira Data Center 8.16 (as a Docker image)
CxFlow 1.6.20 (from the `feature/bb_post_webhook` branch merged with head of `develop`)
BitBucket Cloud (using native web hooks)

### PR DESCRIPTION
**Pull request by nleach999**
### Description

Implementation of BitBucket Server third party webhook plugin Post Web Hooks resolves #651.  Embedded wiki files have been updated to reflect the change.  As part of the implementation, this fixes #650 to avoid additional scans by handling the MERGED event.

As part of the customer's deployment, they needed to have the ability to use multiple instances of BitBucket server to test the configuration and workflow before using in their production instance.  As such, this resolves #674 with changes that allow for multiple BitBucket servers.  The implementation may need some work given when looking at the multi-SCM feature, it was written to accommodate GitHub/GitLab type configurations where there is a URL for the SCM and a URL for the API.  Since BitBucket uses one URL for the SCM and an additional "api-path" configuration, the "optional-instances" clause is configured differently to make multi-SCM with BBS work.

UPDATE: Also resolves #699 out of necessity for deployment.

### Testing

Multi-SCM testing was done with a BB Server as the primary instance, a BB Server and BB Cloud as secondary instances.  Issue #675 will remain open until testing is performed with BB Cloud as the primary SCM with one or more BB Servers as secondary.  

Currently it is deployed and functional at a customer site with their production BB Server as the primary and their sandbox BB Server as the secondary. 

The Post Web Hook plugin was also tested locally using BB Server and is in the customer's environment.  Locally I validated that Post Web Hook events and BB Server native events were handled with no changes from the handling of the BB Server native events.  

Post Web Hook global events are configured in the customer's sandbox and is being used in combination with config-as-code to  provide override configurations on a per-repository basis.  Per-repository Post Web Hook events were tested in my local setup.  The customer has native BB Server events coming from their production instance, so CxFlow is handling both without issue.

Tested issue #699 with both Jira Data Center and Jira Cloud.

### Checklist

- [x] I have added documentation for new/changed functionality in this PR (if applicable).  
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used

### CODE REVIEW

**Comment by MithileshPawar** [comment]
Hi @nleach999 , to run the full pipeline for the PR, the source branch needs to be created from the same repo (cxflow) and the branch name should start with 'pr-'.

**Comment by nleach999** [comment]
@MithileshPawar I don't have permissions to create a branch under checkmarx-ltd repos.  You'll probably have to do what Ken did for my [last PR](https://github.com/checkmarx-ltd/cx-flow/pull/481) that originated from my repo by [re-targeting this PR and merging it](https://github.com/checkmarx-ltd/cx-flow/pull/482) to a branch that meets the naming criteria.

**Comment by MithileshPawar** [comment]
Hi, @nleach999, looks like there are some conflicts. Can you try to rebase your branch (nleach999:feature/bb_post_webhooks) with the new base branch (pr-nathan-bitbucket-post-webhooks) ?

**Comment by nleach999** [comment]
@MithileshPawar done, currently shows no conflicts.

**Review by MithileshPawar — APPROVED** [review]

**Pull request merged**
