### PR TITLE
Add scanResubmit property to config-as-code

### PR DESCRIPTION
**Pull request by atheismann**
By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](https://github.com/checkmarx-ltd/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/checkmarx-ltd/open-source-template/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

Add scan-resubmit override flag to Config-As-Code so that a project can be configured to override the global scan-resubmit configuration value.

### Testing

Testing was accomplished through modifying the Config-As-Code file and validating the actions.

### Checklist

- [X] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentation is a Wiki Update, please indicate desired changes within PR MD Comment*
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [X] The correct base branch is being used

### CODE REVIEW

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by AvivCx** [comment]
Hi @atheismann. did you test the new functionality and verified it was working successfully ?

**Comment by atheismann** [comment]
Yes, @benjaminstokes can confirm our testing.  This functionality is in production already in our system.

**Comment by AvivCx** [comment]
ok thanks @atheismann. I will merge those changes soon, after applying some other changes which we want to release first

**Comment by DhavalPatelPersistent** [comment]
This PR is merged using PR "https://github.com/checkmarx-ltd/cx-flow/pull/884"

**Pull request closed without merging**
