### PR TITLE
remove auto-profile property overwrite in GitHub delete branch processing

### PR DESCRIPTION
**Pull request by milo-minderbinder**

### CODE REVIEW

**Comment by AvivCX** [comment]
Hey @milo-minderbinder. can you say what is the impact of this change?
Is it only cosmetic or real functionality impact?

**Comment by milo-minderbinder** [comment]
@AvivCX sorry, should have provided more context. This fixes a breaking issue for our environment. We have the autoProfile property set to `false` in our environment, because when `autoProfile` is enabled, CxFlow hits an exception during commit & PR events when it calls the profile-related GitHub APIs (perhaps because the GitHub Enterprise service account we use does not have the needed scopes/permissions for those APIs) and so that exception causes processing of those event to fail and CxFlow doesn't create the project and/or kick off Checkmarx scans. I think it's apparent that the line this PR deletes was a typo anyway, because it globally overrides the `autoProfile` property on branch deletion events, so we would see things working as normal (`autoProfile` disabled) until a branch deletion event was processed, at which point all other events started failing since `autoProfile` was enabled.

**Comment by AvivCX** [comment]
@olgakil fyi

**Comment by NimrodGolan** [comment]
Closed the PR and opened a new PR #397

**Pull request closed without merging**
