### PR TITLE
Add github app token generation

### PR DESCRIPTION
**Pull request by GregoireW**
### Description

GitHub apps is a convenient way to get token instead of a user token. Here a way to integrate this.

I also added a doc "github_example" to have a reference file.

### CODE REVIEW

**Comment by GregoireW** [comment]
Note: 
- On the configuration side, I had to remove the "/repos" from github-api url, so it means adding it everywhere it was used.

- On the doc, I'm able to make PR work, but not sure how issues can be created.

**Comment by GregoireW** [comment]
I based the bug tracker parameter on the defined type, but for GitHub issue, it can be `GitHub` as on PR there is an overload to use `GITHUBPULL`.  I modify the example with the correct value and I added a picture of an issue.

**Comment by AvivCX** [comment]
@GregoireW  thank you for the enhancement and the detailed explanation
while we want to add this functionality, I see that the current implementation would break the current behavior and won't work with user token.
since we want to maintain backward compatibility, and support both options to register github, can you please suggest a solution to support both?

**Comment by GregoireW** [comment]
> since we want to maintain backward compatibility, and support both options to register github, can you please suggest a solution to support both?

The `GitHubAuthService` is build to deliver a user token if no github apps is given. 

If you use:

```yaml
github:
  app:
    id: 9876
    org: your_github_org
    # Secret key is the content of the GitHub app private key you converted in the previous step.
    secret-key: |
      -----BEGIN PRIVATE KEY-----
```

then the github app is used to generate the token

if you use:

```yaml
github:
  token: xxxxxx
```
without declaring an app, then it is this token that will be used.


I currently  rebase the code against the latest version, I will tell you when this is ok.

**Comment by GregoireW** [comment]
@AvivCX  I try to launch test on my computer but got some issue with "jira". How to you simulate this server ?

**Comment by AvivCX** [comment]
@GregoireW our convention to run full CI tests (including jira tests), is to change the branch name to 'pr-branchname' - this will trigger all the automation tests

**Pull request closed without merging**
