### PR TITLE
Removed Jira as the default bug tracker

### PR DESCRIPTION
**Pull request by MithileshPawar**
By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](https://github.com/checkmarx-ltd/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/checkmarx-ltd/open-source-template/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

> Removed Jira as the default bugtracker from the default application.yml since it was causing an exception in some scenarios.

### Testing

> Manual Testing

### Checklist

- [x] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentation is a Wiki Update, please indicate desired changes within PR MD Comment*
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used

### CODE REVIEW

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by cxflowtestuser** [comment]
Logo<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 1405 vulnerabilities<br />High&nbsp;**0 High**<br />Medium&nbsp;**53 Medium**<br />Low&nbsp;**1246 Low**<br />Info&nbsp;**106 Info**<br />
### Violation Summary
Medium&nbsp;**11** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1057058&projectid=1775)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[75](https://github.com/checkmarx-ltd/cx-flow/blob/pr-remove-jira-from-ymls/src/main/java/com/checkmarx/flow/controller/bitbucket/cloud/BitbucketCloudController.java#L75) |Medium|Unchecked_Input_for_Loop_Condition|src/main/java/com/checkmarx/flow/controller/bitbucket/cloud/BitbucketCloudController.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1057058&projectid=1775&pathid=73)
[60](https://github.com/checkmarx-ltd/cx-flow/blob/pr-remove-jira-from-ymls/src/main/java/com/checkmarx/flow/service/ExternalScriptService.java#L60) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/service/ExternalScriptService.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1057058&projectid=1775&pathid=50)
[213](https://github.com/checkmarx-ltd/cx-flow/blob/pr-remove-jira-from-ymls/src/main/java/com/checkmarx/flow/utils/ScanUtils.java#L213) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/utils/ScanUtils.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1057058&projectid=1775&pathid=7)
[100](https://github.com/checkmarx-ltd/cx-flow/blob/pr-remove-jira-from-ymls/src/main/java/com/checkmarx/flow/controller/GitHubController.java#L100) [241](https://github.com/checkmarx-ltd/cx-flow/blob/pr-remove-jira-from-ymls/src/main/java/com/checkmarx/flow/controller/GitHubController.java#L241) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/controller/GitHubController.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1057058&projectid=1775&pathid=11)
[67](https://github.com/checkmarx-ltd/cx-flow/blob/pr-remove-jira-from-ymls/src/main/java/com/checkmarx/flow/controller/FlowController.java#L67) [70](https://github.com/checkmarx-ltd/cx-flow/blob/pr-remove-jira-from-ymls/src/main/java/com/checkmarx/flow/controller/FlowController.java#L70) [71](https://github.com/checkmarx-ltd/cx-flow/blob/pr-remove-jira-from-ymls/src/main/java/com/checkmarx/flow/controller/FlowController.java#L71) [76](https://github.com/checkmarx-ltd/cx-flow/blob/pr-remove-jira-from-ymls/src/main/java/com/checkmarx/flow/controller/FlowController.java#L76) [78](https://github.com/checkmarx-ltd/cx-flow/blob/pr-remove-jira-from-ymls/src/main/java/com/checkmarx/flow/controller/FlowController.java#L78) [137](https://github.com/checkmarx-ltd/cx-flow/blob/pr-remove-jira-from-ymls/src/main/java/com/checkmarx/flow/controller/FlowController.java#L137) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/controller/FlowController.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1057058&projectid=1775&pathid=23)

**Comment by jbrotsos** [comment]
@MithileshPawar should it be GitHub or NONE?

**Comment by MithileshPawar** [comment]
> @MithileshPawar should it be GitHub or NONE?

Updated the default bugtracker to 'None'.

**Review by jbrotsos — APPROVED** [review]

**Review by AvivCx — APPROVED** [review]

**Pull request merged**
