### PR TITLE
Added new GitLab template file, versioned it, moved previous template

### PR DESCRIPTION
**Pull request by jbrotsos**
Created a new GitLab template, versioned it, moved previous file into a new directory.

By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](https://github.com/checkmarx-ts/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/checkmarx-ltd/open-source-template/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

- Need to add more variable options for our GitLab template
- Need to place the template file in a more appropriate directory
- Need to version the template files

### References

> Include supporting link to GitHub Issue/PR number

### Testing

> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.

### Checklist

- [x] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentation is a Wiki Update, please indicate desired changes within PR MD Comment*
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used

### CODE REVIEW

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by cxflowtestuser** [comment]
Logo<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 1168 vulnerabilities<br />High&nbsp;**0 High**<br />Medium&nbsp;**3 Medium**<br />Low&nbsp;**1091 Low**<br />Info&nbsp;**74 Info**<br />
### Violation Summary
Medium&nbsp;**3** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1053317&projectid=1255)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[60](https://github.com/checkmarx-ltd/cx-flow/blob/add-gitlab-template/src/main/java/com/checkmarx/flow/service/ExternalScriptService.java#L60) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/service/ExternalScriptService.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1053317&projectid=1255&pathid=9)
[67](https://github.com/checkmarx-ltd/cx-flow/blob/add-gitlab-template/src/main/java/com/checkmarx/flow/controller/FlowController.java#L67) [70](https://github.com/checkmarx-ltd/cx-flow/blob/add-gitlab-template/src/main/java/com/checkmarx/flow/controller/FlowController.java#L70) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/controller/FlowController.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1053317&projectid=1255&pathid=7)

**Review by MithileshPawar — APPROVED** [review]

**Comment by jbrotsos** [comment]
@AvivCx

**Comment by jbrotsos** [comment]
Created a new PR with 'pr-' prefix

**Pull request closed without merging**
