### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by miguelfreitas93**
By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](https://github.com/checkmarx-ts/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/checkmarx-ltd/open-source-template/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change.

### References

> Include supporting link to GitHub Issue/PR number

### Testing

> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentation is a Wiki Update, please indicate desired changes within PR MD Comment*
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used

### CODE REVIEW

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by cxflowtestuser** [comment]
Logo<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 1526 vulnerabilities<br />High&nbsp;**0 High**<br />Medium&nbsp;**46 Medium**<br />Low&nbsp;**1372 Low**<br />Info&nbsp;**108 Info**<br />
### Violation Summary
Medium&nbsp;**11** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1051992&projectid=1175)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[60](https://github.com/checkmarx-ltd/cx-flow/blob/patch-1/src/main/java/com/checkmarx/flow/service/ExternalScriptService.java#L60) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/service/ExternalScriptService.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1051992&projectid=1175&pathid=52)
[67](https://github.com/checkmarx-ltd/cx-flow/blob/patch-1/src/main/java/com/checkmarx/flow/controller/FlowController.java#L67) [70](https://github.com/checkmarx-ltd/cx-flow/blob/patch-1/src/main/java/com/checkmarx/flow/controller/FlowController.java#L70) [71](https://github.com/checkmarx-ltd/cx-flow/blob/patch-1/src/main/java/com/checkmarx/flow/controller/FlowController.java#L71) [76](https://github.com/checkmarx-ltd/cx-flow/blob/patch-1/src/main/java/com/checkmarx/flow/controller/FlowController.java#L76) [78](https://github.com/checkmarx-ltd/cx-flow/blob/patch-1/src/main/java/com/checkmarx/flow/controller/FlowController.java#L78) [137](https://github.com/checkmarx-ltd/cx-flow/blob/patch-1/src/main/java/com/checkmarx/flow/controller/FlowController.java#L137) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/controller/FlowController.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1051992&projectid=1175&pathid=23)
[100](https://github.com/checkmarx-ltd/cx-flow/blob/patch-1/src/main/java/com/checkmarx/flow/controller/GitHubController.java#L100) [241](https://github.com/checkmarx-ltd/cx-flow/blob/patch-1/src/main/java/com/checkmarx/flow/controller/GitHubController.java#L241) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/controller/GitHubController.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1051992&projectid=1175&pathid=11)
[213](https://github.com/checkmarx-ltd/cx-flow/blob/patch-1/src/main/java/com/checkmarx/flow/utils/ScanUtils.java#L213) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/utils/ScanUtils.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1051992&projectid=1175&pathid=7)
[253](https://github.com/checkmarx-ltd/cx-flow/blob/patch-1/src/main/java/com/checkmarx/flow/controller/BitbucketServerController.java#L253) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/controller/BitbucketServerController.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1051992&projectid=1175&pathid=48)

**Review by MithileshPawar — APPROVED** [review]

**Comment by MithileshPawar** [comment]
The branch name must start with 'pr-' and the branch can be made from the cxflow repo rather than the forked repo.

**Comment by miguelfreitas93** [comment]
@MithileshPawar feel free to cancel this PR and do the changes on the repo itself

**Pull request closed without merging**
