### PR TITLE
Pr parse mode implementation for sca

### PR DESCRIPTION
**Pull request by DadasoBanagar**
Description:
Parse mode suport for SCA product in CX-Flow.Now we can use --parse mode in cx-flow and create the issue on different bug tracker(like Jira,Json,Sarif etc).

References:
https://github.com/checkmarx-ltd/checkmarx-spring-boot-java-sdk/pull/205

Testing:

Below are the test case:

A]
  Generate report from ScaResolver tool and use this report in parse mode command execution.
  
B]
Step 1: run scan mode

 run the scan command  through CLI(i.e from cmd) and generate scan report on sca portal.

Use below  scan command:-

java -jar cx-flow-1.6.31.jar --spring.config.location="<location of your application.yml>" --scan --f="<location of your  cx-flow>" --cx-team= "CxServer" --cx-project="<project name>" --app="<app name>"

 Step2:

 From sca portal export the scan report in xml format. 

 Step 3:parse mode

 Use above exported xml file and run parse mode command through CLI(i.e from cmd).And parse report is generated on configured bug tracker in application.yml file.

Use below parse command for sca parse:-

java -jar cx-flow-1.6.31.jar --spring.config.location="<location of application.yml>l" --parse --f="<location of exported xml file report from sca portal>" --cx-team= "CxServer" --cx-project="<project name>" --app="<app name>"

Step 3:After succesfully executing above parse command then exporeted xml file report will create on configured bugtracker(like Jira,Json,Sarif etc.)

### CODE REVIEW

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by DadasoBanagar** [comment]
parse mode support for sca product in cx-flow

**Comment by DadasoBanagar** [comment]
parse mode support for sca product in cx-flow

**Comment by DadasoBanagar** [comment]
parse mode support for sca product in cx-flow.

**Comment by DadasoBanagar** [comment]
parse mode support for sca product in cx-flow

**Comment by DadasoBanagar** [comment]
parse mode support for sca product in cx-flow

**Review by DhavalPatelPersistent — DISMISSED** [review]

**Review by DhavalPatelPersistent — APPROVED** [review]

**Pull request merged**
