### PR TITLE
Pr ofer@205 improve end to end tests

### PR DESCRIPTION
**Pull request by ofersk**
### Description

We noticed that when we run the E2E flows of Cx-Flow we are missing important log information.
This change only changes the default logging levels (in the main application.yml and in the tests' application.yml)

### References

this solves the change requested in user story  [205](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/205)

### Testing

no new tests are needed. (the E2E's results xml changed to include more info)

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentaiton is a Wiki Update, please indicate desired changes within PR MD Comment*
- [X] All active GitHub checks for tests, formatting, and security are passing
- [X] The correct base branch is being used

### CODE REVIEW

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by cxflowtestuser** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010665&projectid=224)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|112
Low|1407
Informational|38

#### Violation Summary
Severity|Count
---|---

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---

**Comment by AvivCX** [comment]
@ofersk the latest CI run doesn't have the required logs

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by cxflowtestuser** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010666&projectid=224)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|112
Low|1407
Informational|38

#### Violation Summary
Severity|Count
---|---

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---

**Comment by ofersk** [comment]
was fixed using another pr.

**Pull request closed without merging**
