### PR TITLE
Fix postback Scan Reports

### PR DESCRIPTION
**Pull request by atheismann**
By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](https://github.com/checkmarx-ltd/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/checkmarx-ltd/open-source-template/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

Extra fields existed in the Scan Comments for a "PostBack" scan.  Those fields were not recognized by the Postback Parser on the `/postbackAction` endpoint.  The missing fields were added and tested.

Also, the Postback mode report generation does not use the GitHub App.  Fields were added to the scan comments to pass the installation id so that CxFlow can post as the GitHub app.

### References

Fix postback - Re: Issue #939 

### Testing

Testing was completed by deploying into our development environment with multiple shards.

Manual Testing:
Enable Sharding and PostBack mode in Cxflow.
Trigger scan from GitHub
Results should post back to the Comment once complete.

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentation is a Wiki Update, please indicate desired changes within PR MD Comment*
- [X] All active GitHub checks for tests, formatting, and security are passing
- [X] The correct base branch is being used

### CODE REVIEW

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by cxflowtestuser** [comment]
Scan not submitted to Checkmarx due to existing Active scan for the same project.

**Comment by jbrotsos** [comment]
@umeshwaghode can you please review?

**Comment by DhavalPatelPersistent** [comment]
Hi @atheismann,

Can you please add more details on post back action in cxflow as well as Checkmarx SAST Sever.
As per document, we need to create cxflow.bat which need to be specify in Checkmarx SAST Server. But we did not understand how this file will be call by Checkmarx SAST Server. Can you please add this configuration septs as well ?

Thanks & Regards,
Dhaval Patel.

**Review by umeshwaghode — APPROVED** [review]
Looks good.

**Pull request merged**
