### PR TITLE
Created a new GitLab template, versioned it, moved previous file into…

### PR DESCRIPTION
**Pull request by jbrotsos**
Created a new GitLab template, versioned it, moved previous file into a new directory.

By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](https://github.com/checkmarx-ts/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/checkmarx-ltd/open-source-template/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

- Need to add more variable options for our GitLab template
- Need to place the template file in a more appropriate directory
- Need to version the template files

### References

N/A

### Testing

Tested using GitLab repos. 

### Checklist

- [x] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentation is a Wiki Update, please indicate desired changes within PR MD Comment*
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used

### CODE REVIEW

**Comment by cxflowtestuser** [comment]
Scan submitted to Checkmarx

**Comment by cxflowtestuser** [comment]
Logo<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 1168 vulnerabilities<br />High&nbsp;**0 High**<br />Medium&nbsp;**3 Medium**<br />Low&nbsp;**1091 Low**<br />Info&nbsp;**74 Info**<br />
### Violation Summary
Medium&nbsp;**3** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1053704&projectid=1278)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[60](https://github.com/checkmarx-ltd/cx-flow/blob/pr-update-gitlab-template/src/main/java/com/checkmarx/flow/service/ExternalScriptService.java#L60) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/service/ExternalScriptService.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1053704&projectid=1278&pathid=9)
[67](https://github.com/checkmarx-ltd/cx-flow/blob/pr-update-gitlab-template/src/main/java/com/checkmarx/flow/controller/FlowController.java#L67) [70](https://github.com/checkmarx-ltd/cx-flow/blob/pr-update-gitlab-template/src/main/java/com/checkmarx/flow/controller/FlowController.java#L70) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/controller/FlowController.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1053704&projectid=1278&pathid=7)

**Review by MithileshPawar — APPROVED** [review]

**Comment by MithileshPawar** [comment]
The full pipeline intended for PR still didn't run. Is it because the source branch is from the forked repo?
@AvivCx any idea bout this?

**Comment by AvivCx** [comment]
yes. you need the branch name to include 'pr-'

**Comment by jbrotsos** [comment]
resubmitted via branch

**Pull request closed without merging**
